baseURL: 'https://www.zellysnyder.com'
languageCode: 'en-us'
title: 'Zelly Snyder'
theme: 'hugo-PaperMod'

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
  minifyOutput: true

params:
  env: production
  title: "Zelly Snyder"
  description: "Zelly Snyder's personal site about Linux, programming, systems design, software development and AI"
  author: "Zelly Snyder"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  showtoc: true
  tocopen: true
  UseHugoToc: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCopyCodeButtons: true
  comments: false
  hidemeta: false
  hideSummary: false

  assets:
    favicon: "/icon/favicon.ico"
    favicon16x16: "/icon/icon16.png"
    favicon32x32: "/icon/icon32.png"
    apple_touch_icon: "/icon/icon180.png"
    safari_pinned_tab: "/icon/safari_pinned_tab.svg"

  homeInfoParams:
    Title: "Welcome to my blog"
    Content: >
      😀

  socialIcons:
    - name: github
      url: "https://github.com/proprietary"
    - name: email
      url: "mailto:zelcon@zelcon.net"

  label:
    text: "Zelly Snyder's blog"
    icon: "/icon/icon.svg"
    iconHeight: 32

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: PGP key
          url: gpg-pgp-public-key
          weight: 5
        - name: Archive
          url: archives
          weight: 10
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
